---
name: Bazzite Wallpapers
on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Release for Bazzite Wallpapers
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      container_tag: ${{ steps.tag.outputs.container_tag }}
    # We need a newish version of kimageformats, 24.04 doesn't have it
    container: docker.io/library/ubuntu:25.04@sha256:103c7471649a4fd9996fe73dff20f46082e4e0f0f6240c91954b8b09c38b6faf

    steps:

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
      - name: Create tarball
        shell: bash
        run: |
          mkdir -p output/packaging/
          cp -R wallpapers/bazzite/* output/packaging/
          cd output/packaging && tar -acvf bazzite-wallpapers.tar.zstd *

      - name: Determine tag
        id: tag
        run: |
          DATE_SUFFIX="$(date --iso-8601=date)"
          echo "tag=bazzite-v${DATE_SUFFIX}" >> "$GITHUB_OUTPUT"
          echo "container_tag=v${DATE_SUFFIX}" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaging-artifacts
          path: output/packaging/

      - name: Publish release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1
        with:
          tag:   ${{ steps.tag.outputs.tag }}
          allowUpdates: true
          name:  "${{ steps.tag.outputs.tag }}"
          artifacts: "output/packaging/bazzite-wallpapers.tar.zstd"
          token: ${{ secrets.GITHUB_TOKEN }}

  push-image:
    needs: create-release
    uses: ./.github/workflows/push-oci-image.yaml
    with:
      image-name: bazzite-wallpapers
      release-tag: ${{ needs.create-release.outputs.container_tag }}
      flavors: '[""]'
